// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Cn = require("re-classnames/src/Cn.bs.js");
var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var Job$ReactTemplate = require("./Job.bs.js");
var Styles$ReactTemplate = require("./Styles.bs.js");
var Projects$ReactTemplate = require("./data/Projects.bs.js");

function str(prim) {
  return prim;
}

var selfie = "/images/selfie_resize.jpg";

function Index(Props) {
  return React.createElement("div", {
              className: Styles$ReactTemplate.fadeIn
            }, React.createElement("div", undefined, React.createElement("div", {
                      className: Styles$ReactTemplate.center
                    }, React.createElement("h1", {
                          className: Styles$ReactTemplate.mainTitle
                        }, "Matt Pritchard"), React.createElement("h2", {
                          className: Styles$ReactTemplate.subTitle
                        }, "Web Developer"), React.createElement("div", {
                          className: Styles$ReactTemplate.mobileShow
                        }, React.createElement("img", {
                              className: Styles$ReactTemplate.image,
                              alt: "Headshot",
                              src: selfie
                            })), React.createElement("div", {
                          className: Cn.make(/* :: */[
                                Styles$ReactTemplate.mainGrid,
                                /* :: */[
                                  Styles$ReactTemplate.justify,
                                  /* [] */0
                                ]
                              ])
                        }, React.createElement("div", {
                              className: Cn.make(/* :: */[
                                    Styles$ReactTemplate.splitGridLeft,
                                    /* :: */[
                                      Styles$ReactTemplate.singleColText,
                                      /* [] */0
                                    ]
                                  ])
                            }, React.createElement("h3", undefined, "Who Am I?"), React.createElement("p", undefined, "Hi, I'm Matt, a self taught programmer and Senior Front End Developer at ", React.createElement("a", {
                                      href: "https://d3-nyc.com"
                                    }, "D3 NYC"), ". Over the last few years, I've worked with a variety of web technologies and programming languages across a wide range of client work and internal agency projects. As the agency has grown, I've hired and managed a team of three excellent developers, worked with our Account team to solve complex problems, and represented the agency in person with clients to assess their needs and devise novel solutions."), React.createElement("p", undefined, "I have a strong interest in functional programming and typed languages (this site was built with ReasonML!) and constantly push myself to learn something new every day. If you would like to know a little about my professional experience, check out the projects below that I've worked on at D3 NYC!"), React.createElement("p", {
                                  className: Styles$ReactTemplate.bold
                                }, "Contact me: ", React.createElement("a", {
                                      href: "mailto:mattpritchard4@gmail.com"
                                    }, "mattpritchard4@gmail.com"))), React.createElement("div", {
                              className: Cn.make(/* :: */[
                                    Styles$ReactTemplate.splitGridRight,
                                    /* :: */[
                                      Styles$ReactTemplate.mobileHide,
                                      /* [] */0
                                    ]
                                  ])
                            }, React.createElement("img", {
                                  className: Styles$ReactTemplate.image,
                                  src: selfie
                                }))))), React.createElement("div", {
                  className: Styles$ReactTemplate.agencyContainOpen
                }, React.createElement("div", undefined, React.createElement("h2", {
                          className: Styles$ReactTemplate.center
                        }, "Languages and Technical Skills"), React.createElement("br", undefined), React.createElement("ul", undefined, React.createElement("li", undefined, React.createElement("h3", {
                                  className: Styles$ReactTemplate.bold
                                }, "Proficient: "), React.createElement("p", undefined, "JavaScript, Ruby, HTML, CSS, Grid, Bootstrap, SASS, jQuery, Pug, Pollen, Git, Bash, Emacs")), React.createElement("li", undefined, React.createElement("h3", {
                                  className: Styles$ReactTemplate.bold
                                }, "Exposure: "), React.createElement("p", undefined, "React, OCaml, ReasonML, Reason-React, TypeScript, Angular 6/7, GatsbyJS, PHP, Racket, Scheme, C")), React.createElement("li", undefined, React.createElement("h3", {
                                  className: Styles$ReactTemplate.bold
                                }, "CMS/ESP: "), React.createElement("p", undefined, "WordPress, Webflow, Agility Harmony, Sailthru, Braze, Oracle Respnsys, Squarespace, Active Campaign, Exact Target"))), React.createElement("br", undefined)), React.createElement("div", {
                      className: Styles$ReactTemplate.center
                    }, React.createElement("h2", undefined, "Agency Projects"), React.createElement("br", undefined)), $$Array.of_list(List.map((function (job) {
                            return React.createElement(Job$ReactTemplate.make, {
                                        title: job[/* title */0],
                                        client: job[/* client */1],
                                        logo: job[/* logo */2],
                                        description: job[/* description */3]
                                      });
                          }), Projects$ReactTemplate.project))));
}

var make = Index;

var $$default = Index;

exports.str = str;
exports.selfie = selfie;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
