// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");

Css.$$global("body, p, h1, h2, h3", /* :: */[
      Css.fontFamily("Charter Regular"),
      /* [] */0
    ]);

Css.$$global("h2", /* :: */[
      Css.fontSize(Css.em(2.0)),
      /* [] */0
    ]);

var image = Css.style(/* :: */[
      Css.maxWidth(Css.pct(60.0)),
      /* :: */[
        Css.margin(/* auto */-1065951377),
        /* [] */0
      ]
    ]);

var mainTitle = Css.style(/* :: */[
      Css.media("(max-width: 768px)", /* :: */[
            Css.fontSize(Css.em(3.0)),
            /* [] */0
          ]),
      /* :: */[
        Css.media("(min-width: 769px)", /* :: */[
              Css.fontSize(Css.em(4.0)),
              /* [] */0
            ]),
        /* [] */0
      ]
    ]);

var subTitle = Css.style(/* :: */[
      Css.media("(max-width: 768px)", /* :: */[
            Css.fontSize(Css.em(2.0)),
            /* [] */0
          ]),
      /* :: */[
        Css.media("(min-width: 769px)", /* :: */[
              Css.fontSize(Css.em(3.0)),
              /* [] */0
            ]),
        /* [] */0
      ]
    ]);

var center = Css.style(/* :: */[
      Css.textAlign(/* center */98248149),
      /* [] */0
    ]);

var justify = Css.style(/* :: */[
      Css.textAlign(/* justify */62250832),
      /* [] */0
    ]);

var mainGrid = Css.style(/* :: */[
      Css.gridTemplateRows(/* :: */[
            /* auto */-1065951377,
            /* :: */[
              /* auto */-1065951377,
              /* [] */0
            ]
          ]),
      /* :: */[
        Css.display(/* grid */-999565626),
        /* [] */0
      ]
    ]);

var fullWidthGrid = Css.style(/* :: */[
      Css.gridColumnStart(0),
      /* :: */[
        Css.gridColumnEnd(2),
        /* :: */[
          Css.gridRowStart(0),
          /* :: */[
            Css.gridRowEnd(1),
            /* :: */[
              Css.display(/* grid */-999565626),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var splitGridLeft = Css.style(/* :: */[
      Css.gridColumnStart(0),
      /* :: */[
        Css.gridColumnEnd(1),
        /* :: */[
          Css.gridRowStart(1),
          /* :: */[
            Css.gridRowEnd(2),
            /* :: */[
              Css.display(/* grid */-999565626),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var splitGridRight = Css.style(/* :: */[
      Css.gridColumnStart(1),
      /* :: */[
        Css.gridColumnEnd(2),
        /* :: */[
          Css.gridRowStart(1),
          /* :: */[
            Css.gridRowEnd(2),
            /* :: */[
              Css.display(/* grid */-999565626),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var mobileHide = Css.style(/* :: */[
      Css.media("(max-width: 768px)", /* :: */[
            Css.display(/* none */-922086728),
            /* [] */0
          ]),
      /* [] */0
    ]);

var mobileShow = Css.style(/* :: */[
      Css.media("(max-width: 768px)", /* :: */[
            Css.display(/* block */888960333),
            /* [] */0
          ]),
      /* :: */[
        Css.media("(min-width: 769px)", /* :: */[
              Css.display(/* none */-922086728),
              /* [] */0
            ]),
        /* [] */0
      ]
    ]);

var singleColImage = Css.style(/* :: */[
      Css.media("(max-width: 768px)", /* :: */[
            Css.gridColumnStart(0),
            /* :: */[
              Css.gridColumnEnd(1),
              /* :: */[
                Css.gridRowStart(0),
                /* :: */[
                  Css.gridRowEnd(1),
                  /* :: */[
                    Css.display(/* grid */-999565626),
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]),
      /* [] */0
    ]);

var singleColText = Css.style(/* :: */[
      Css.media("(max-width: 768px)", /* :: */[
            Css.gridColumnStart(0),
            /* :: */[
              Css.gridColumnEnd(1),
              /* :: */[
                Css.gridRowStart(1),
                /* :: */[
                  Css.gridRowEnd(2),
                  /* :: */[
                    Css.display(/* grid */-999565626),
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]),
      /* [] */0
    ]);

var fadeInAnimation = Css.keyframes(/* :: */[
      /* tuple */[
        0,
        /* :: */[
          Css.opacity(0.0),
          /* [] */0
        ]
      ],
      /* :: */[
        /* tuple */[
          100,
          /* :: */[
            Css.opacity(1.0),
            /* [] */0
          ]
        ],
        /* [] */0
      ]
    ]);

var fadeIn = Css.style(/* :: */[
      Css.animationName(fadeInAnimation),
      /* :: */[
        Css.animationDuration(3000),
        /* [] */0
      ]
    ]);

var agencyContainOpen = Css.style(/* :: */[
      Css.height(Css.pct(100.0)),
      /* [] */0
    ]);

var jobPaddingTop = Css.style(/* :: */[
      Css.paddingTop(Css.px(30)),
      /* [] */0
    ]);

var jobPaddingBottom = Css.style(/* :: */[
      Css.paddingBottom(Css.px(30)),
      /* [] */0
    ]);

var logos = Css.style(/* :: */[
      Css.height(Css.px(30)),
      /* :: */[
        Css.padding(Css.px(5)),
        /* [] */0
      ]
    ]);

var bold = Css.style(/* :: */[
      Css.fontFamily("Charter Bold"),
      /* [] */0
    ]);

exports.image = image;
exports.mainTitle = mainTitle;
exports.subTitle = subTitle;
exports.center = center;
exports.justify = justify;
exports.mainGrid = mainGrid;
exports.fullWidthGrid = fullWidthGrid;
exports.splitGridLeft = splitGridLeft;
exports.splitGridRight = splitGridRight;
exports.mobileHide = mobileHide;
exports.mobileShow = mobileShow;
exports.singleColImage = singleColImage;
exports.singleColText = singleColText;
exports.fadeInAnimation = fadeInAnimation;
exports.fadeIn = fadeIn;
exports.agencyContainOpen = agencyContainOpen;
exports.jobPaddingTop = jobPaddingTop;
exports.jobPaddingBottom = jobPaddingBottom;
exports.logos = logos;
exports.bold = bold;
/*  Not a pure module */
